
--CREATE DATABASE IF NOT EXISTS Test;
--USE Test;

DROP TABLE IF EXISTS ITEMS;

CREATE TABLE ITEMS(
	itemno INTEGER AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR2(20) NOT NULL,
	amount INTEGER NOT NULL,
	inventorycode VARCHAR2(20) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS ITEM_SEQUENCE_ID START WITH (select min(itemno) + 1 from ITEMS);